version: '3'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stuHub
    volumes:
      - ./pg-data/:/var/lib/postgresql/data/

volumes:
  pg-data: