// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	UserID    int64        `json:"user_id"`
	Done      sql.NullBool `json:"done"`
	CreatedAt time.Time    `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
